### ISSUE TITLE
KeyError in a del

### ISSUE THREAD

**Issue by fpoulain** [wagtail/django-modelcluster#132]
Hi,

I encountered a KeyError in a del:

```
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 105, in wrapper
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/wagtail/admin/auth.py", line 165, in decorated_view
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/options.py", line 352, in create_view
    return view_class.as_view(**kwargs)(request)
  File "venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/views.py", line 614, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/views.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/views.py", line 168, in form_valid
    instance = form.save()
  File "venv/lib/python3.7/site-packages/modelcluster/forms.py", line 373, in save
    formset.save(commit=commit)
  File "venv/lib/python3.7/site-packages/modelcluster/forms.py", line 118, in save
    manager.commit()
  File "venv/lib/python3.7/site-packages/modelcluster/fields.py", line 210, in commit
    del self.instance._cluster_related_objects[relation_name]
```

I am using :
Django                        2.2.15
django-modelcluster           5.0.2
wagtail                       2.7.4

**Comment by fpoulain** [comment]
This bug is quite blocking for me. Is there anyway I can help?

**Comment by gasman** [comment]
Glad you got it sorted! Yes, I think the custom logic on `EventRange.save` is what's causing the problems here - I don't think there's really anything that can be done in django-modelcluster to avoid that.
