### ISSUE TITLE
Formset test failures on Django 1.11a1

### ISSUE THREAD

**Issue by gasman** [wagtail/django-modelcluster#66]
Several tests are failing against Django 1.11a1, due to this change:

https://github.com/django/django/commit/181f492ad021aeb43105aa9d38106ad7baf00211
https://code.djangoproject.com/ticket/27416

	Creating test database for alias 'default'...
	System check identified no issues (0 silenced).
	..............................FF.........F..........F........................x..
	======================================================================
	FAIL: test_formsets_from_model_superclass_are_exposed (tests.tests.test_cluster_form.ClusterFormTest)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/vagrant/libs/django-modelcluster/tests/tests/test_cluster_form.py", line 451, in test_formsets_from_model_superclass_are_exposed
	    self.assertEqual(instance.reviews.count(), 1)
	AssertionError: 0 != 1

	======================================================================
	FAIL: test_formsets_from_model_superclass_with_explicit_formsets_def (tests.tests.test_cluster_form.ClusterFormTest)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/vagrant/libs/django-modelcluster/tests/tests/test_cluster_form.py", line 482, in test_formsets_from_model_superclass_with_explicit_formsets_def
	    self.assertEqual(instance.reviews.count(), 1)
	AssertionError: 0 != 1

	======================================================================
	FAIL: test_child_updates_without_ids (tests.tests.test_formset.ChildFormsetTest)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/vagrant/libs/django-modelcluster/tests/tests/test_formset.py", line 240, in test_child_updates_without_ids
	    self.assertEqual(2, beatles.members.count())
	AssertionError: 2 != 1

	======================================================================
	FAIL: test_incoming_formset_data (tests.tests.test_formset.TransientFormsetTest)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/vagrant/libs/django-modelcluster/tests/tests/test_formset.py", line 43, in test_incoming_formset_data
	    self.assertEqual(2, len(members))
	AssertionError: 2 != 1

	----------------------------------------------------------------------
	Ran 80 tests in 0.608s

	FAILED (failures=4, expected failures=1)

**Comment by gasman** [comment]
Fixed in #70
