### ISSUE TITLE
Doesn't work with swappable models

### ISSUE THREAD

**Issue by benjaoming** [wagtail/django-modelcluster#79]
I'm trying to create swappable models for wagtail-blog and seeing that `makemigrations` breaks because django's migration app cache isn't able to produce a correct lazy reference for `ParentalKey`.

Traceback:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "site-packages/django/core/management/commands/makemigrations.py", line 176, in handle
    migration_name=self.migration_name,
  File "site-packages/django/db/migrations/autodetector.py", line 47, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "site-packages/django/db/migrations/autodetector.py", line 132, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "site-packages/django/db/migrations/state.py", line 180, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "site-packages/django/db/migrations/state.py", line 249, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: <function resolve_related_class at 0x7f4d8539b578> contains a lazy reference to pages.blogpagetag, but app 'pages' doesn't provide model 'blogpagetag'.
<function resolve_through_model at 0x7f4d8539b8c0> contains a lazy reference to pages.blogcategoryblogpage, but app 'pages' doesn't provide model 'blogcategoryblogpage'.
The field blog.BlogCategoryBlogPage.page was declared with a lazy reference to 'pages.blogpage', but app 'pages' doesn't provide model 'blogpage'.
The field blog.BlogPageTag.content_object was declared with a lazy reference to 'pages.blogpage', but app 'pages' doesn't provide model 'blogpage'.
```

In the traceback, `blog.BlogCategoryBlogPage.page` and `blog.BlogPageTag.content_object` are both `ParentalKey` fields. They both belong to models which have been swapped out.

The question is how to stop `model_checks._check_lazy_references` from checking these fields.

**Comment by benjaoming** [comment]
Maybe it's caused by something else.

I was just unlucky enough that precisely the two only fields that failed were `ParentalKey`, but changing them to `ForeignKey` hasn't made a difference.

**Comment by gasman** [comment]
Closing for now - please update if you can find a reproducible test case that fails for ParentalKey.

**Comment by benjaoming** [comment]
Yeah, right now my debugging is sadly taking me to places in `django.db.migrations` that I don't want to see :)

**Comment by benjaoming** [comment]
Thanks for the project @gasman :)
